# 1. 빌드(Build) Phase

# FROM node:16-alpine as builder
FROM node:16-alpine

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

# 2. 실행(Run) Phase

# https://hub.docker.com/_/nginx
FROM nginx:1.25.3-alpine
EXPOSE 80

COPY /app/build /usr/share/nginx/html
# COPY --from=builder /app/build /usr/share/nginx/html

